package kz.zeroops.api;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/agent") public class AgentController {
 private final EnrollmentTokenRepository enrollments; private final ManagedServerRepository servers; private final ServerHeartbeatRepository heartbeats; private final DeploymentRepository deployments; private final DeploymentLogRepository logs; private final ManifestSigner manifests; private final java.security.SecureRandom random=new java.security.SecureRandom();
 public AgentController(EnrollmentTokenRepository enrollments,ManagedServerRepository servers,ServerHeartbeatRepository heartbeats,DeploymentRepository deployments,DeploymentLogRepository logs,ManifestSigner manifests){this.enrollments=enrollments;this.servers=servers;this.heartbeats=heartbeats;this.deployments=deployments;this.logs=logs;this.manifests=manifests;}
 @PostMapping("/enroll") public AgentCredential enroll(@Valid @RequestBody EnrollRequest request){EnrollmentToken token=enrollments.findByTokenHash(ServerController.hash(request.token())).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Enrollment token is invalid"));if(!token.active())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Enrollment token is expired, used or revoked");ManagedServer s=token.getServer();String raw=secret();s.setAgentTokenHash(ServerController.hash(raw));s.status(ServerStatus.OFFLINE);servers.save(s);token.use();enrollments.save(token);return new AgentCredential(s.getId(),raw,Instant.now().plus(Duration.ofDays(30)));}
 @PostMapping("/{id}/heartbeat") @ResponseStatus(HttpStatus.NO_CONTENT) public void heartbeat(@PathVariable Long id,@RequestHeader("X-Agent-Token") String credential,@Valid @RequestBody HeartbeatRequest r){ManagedServer s=servers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Server not found"));if(s.getAgentTokenHash()==null||!java.security.MessageDigest.isEqual(s.getAgentTokenHash().getBytes(),ServerController.hash(credential).getBytes()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Agent credential is invalid");if(s.getStatus()==ServerStatus.DISABLED)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Server is disabled");heartbeats.save(new ServerHeartbeat(s,r.cpuPercent(),r.ramPercent(),r.diskPercent(),r.managedContainers(),r.dockerVersion(),r.os(),r.agentVersion()));s.seen();servers.save(s);}
 @GetMapping("/{id}/deployments/next") @Transactional public ResponseEntity<ManifestSigner.SignedManifest> next(@PathVariable Long id,@RequestHeader("X-Agent-Token") String credential){ManagedServer s=authenticated(id,credential);if(s.getStatus()!=ServerStatus.ONLINE)throw new ResponseStatusException(HttpStatus.CONFLICT,"Server is not available");return deployments.findQueuedForServer(id).stream().findFirst().map(d->{ManifestSigner.SignedManifest manifest=manifests.issue(d);d.moveTo(DeploymentStatus.CHECKOUT);deployments.save(d);appendLog(d,"Deployment leased to enrolled Agent; awaiting verified execution.");return ResponseEntity.ok(manifest);}).orElseGet(()->ResponseEntity.noContent().build());}
 @PostMapping("/{serverId}/deployments/{deploymentId}/result") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void result(@PathVariable Long serverId,@PathVariable Long deploymentId,@RequestHeader("X-Agent-Token") String credential,@Valid @RequestBody ResultRequest r){authenticated(serverId,credential);Deployment d=deployments.findWithProjectAndOwnerById(deploymentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Deployment not found"));if(d.getProject().getTargetServer()==null||!d.getProject().getTargetServer().getId().equals(serverId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Deployment belongs to another server");if(d.getStatus()==DeploymentStatus.SUCCESS||d.getStatus()==DeploymentStatus.FAILED) return;d.moveTo(r.success()?DeploymentStatus.SUCCESS:DeploymentStatus.FAILED,r.success()?null:r.reason());deployments.save(d);appendLog(d,r.message());}
 private ManagedServer authenticated(Long id,String credential){ManagedServer s=servers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Server not found"));if(s.getAgentTokenHash()==null||!java.security.MessageDigest.isEqual(s.getAgentTokenHash().getBytes(),ServerController.hash(credential).getBytes()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Agent credential is invalid");return s;}
 private void appendLog(Deployment deployment,String message){int line=logs.findByDeploymentIdOrderByLineNumberAsc(deployment.getId()).size()+1;logs.save(new DeploymentLog(deployment,line,message));}
 private String secret(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} public record EnrollRequest(@NotBlank String token){} public record AgentCredential(Long serverId,String credential,Instant expiresAt){} public record HeartbeatRequest(@Min(0) @Max(100) int cpuPercent,@Min(0) @Max(100) int ramPercent,@Min(0) @Max(100) int diskPercent,@Min(0) int managedContainers,@Size(max=100) String dockerVersion,@Size(max=100) String os,@Size(max=100) String agentVersion){} public record ResultRequest(boolean success,@NotBlank @Size(max=1000) String message,@Size(max=1000) String reason){}
}
