package kz.zeroops.api;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/agent") public class AgentController {
 private final EnrollmentTokenRepository enrollments; private final ManagedServerRepository servers; private final ServerHeartbeatRepository heartbeats; private final java.security.SecureRandom random=new java.security.SecureRandom();
 public AgentController(EnrollmentTokenRepository enrollments,ManagedServerRepository servers,ServerHeartbeatRepository heartbeats){this.enrollments=enrollments;this.servers=servers;this.heartbeats=heartbeats;}
 @PostMapping("/enroll") public AgentCredential enroll(@Valid @RequestBody EnrollRequest request){EnrollmentToken token=enrollments.findByTokenHash(ServerController.hash(request.token())).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Enrollment token is invalid"));if(!token.active())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Enrollment token is expired, used or revoked");ManagedServer s=token.getServer();String raw=secret();s.setAgentTokenHash(ServerController.hash(raw));s.status(ServerStatus.OFFLINE);servers.save(s);token.use();enrollments.save(token);return new AgentCredential(s.getId(),raw,Instant.now().plus(Duration.ofDays(30)));}
 @PostMapping("/{id}/heartbeat") @ResponseStatus(HttpStatus.NO_CONTENT) public void heartbeat(@PathVariable Long id,@RequestHeader("X-Agent-Token") String credential,@Valid @RequestBody HeartbeatRequest r){ManagedServer s=servers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Server not found"));if(s.getAgentTokenHash()==null||!java.security.MessageDigest.isEqual(s.getAgentTokenHash().getBytes(),ServerController.hash(credential).getBytes()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Agent credential is invalid");if(s.getStatus()==ServerStatus.DISABLED)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Server is disabled");heartbeats.save(new ServerHeartbeat(s,r.cpuPercent(),r.ramPercent(),r.diskPercent(),r.managedContainers(),r.dockerVersion(),r.os(),r.agentVersion()));s.seen();servers.save(s);}
 private String secret(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} public record EnrollRequest(@NotBlank String token){} public record AgentCredential(Long serverId,String credential,Instant expiresAt){} public record HeartbeatRequest(@Min(0) @Max(100) int cpuPercent,@Min(0) @Max(100) int ramPercent,@Min(0) @Max(100) int diskPercent,@Min(0) int managedContainers,@Size(max=100) String dockerVersion,@Size(max=100) String os,@Size(max=100) String agentVersion){}
}
