package kz.zeroops.api;

public enum DeploymentStatus {
  CREATED, QUEUED, CHECKOUT, ANALYZING, BUILDING, PUSHING_IMAGE, DEPLOYING,
  HEALTH_CHECKING, SWITCHING_TRAFFIC, SUCCESS, FAILED, CANCELLED, ROLLED_BACK
}
