package kz.zeroops.api;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.net.URI; import java.net.http.*; import java.time.Duration; import java.util.List;
import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/v1/github")
public class GitHubController {
 private final GitHubConnectionRepository connections; private final CurrentUser current; private final SecretCodec secrets; private final ObjectMapper json;
 public GitHubController(GitHubConnectionRepository connections,CurrentUser current,SecretCodec secrets,ObjectMapper json){this.connections=connections;this.current=current;this.secrets=secrets;this.json=json;}
 @GetMapping("/connections") public List<ConnectionResponse> list(){return connections.findAllByOwnerIdOrderByCreatedAtDesc(current.require().getId()).stream().map(ConnectionResponse::from).toList();}
 @PostMapping("/connections") @ResponseStatus(HttpStatus.CREATED) public ConnectionResponse connect(@Valid @RequestBody ConnectRequest request){String account=verify(request.token());AppUser user=current.require();GitHubConnection c=new GitHubConnection(user,account,secrets.encrypt(request.token()));return ConnectionResponse.from(connections.save(c));}
 @DeleteMapping("/connections/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void disconnect(@PathVariable Long id){GitHubConnection c=connections.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"GitHub connection not found"));if(!c.getOwner().getId().equals(current.require().getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Connection access denied");connections.delete(c);}
 @GetMapping("/branches") public List<String> branches(@RequestParam String repository){GitHubConnection c=connections.findFirstByOwnerIdOrderByCreatedAtDesc(current.require().getId()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Connect GitHub before listing branches"));validateRepo(repository);try{JsonNode nodes=json.readTree(call("https://api.github.com/repos/"+repository+"/branches",secrets.decrypt(c.getTokenCiphertext())));if(!nodes.isArray())throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"Unexpected GitHub response");return java.util.stream.StreamSupport.stream(nodes.spliterator(),false).map(n->n.path("name").asText()).toList();}catch(ResponseStatusException e){throw e;}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"GitHub branches are unavailable");}}
 private String verify(String token){try{JsonNode user=json.readTree(call("https://api.github.com/user",token));String login=user.path("login").asText();if(login.isBlank())throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"GitHub token is invalid");return login;}catch(ResponseStatusException e){throw e;}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"GitHub cannot be reached");}}
 private String call(String url,String token)throws Exception{HttpResponse<String> r=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build().send(HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(10)).header("Accept","application/vnd.github+json").header("Authorization","Bearer "+token).header("X-GitHub-Api-Version","2022-11-28").GET().build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()==401)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"GitHub token is invalid or expired");if(r.statusCode()==403)throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"GitHub access denied or rate limit reached");if(r.statusCode()==404)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"GitHub repository was not found");if(r.statusCode()/100!=2)throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"GitHub request failed");return r.body();}
 private void validateRepo(String repo){if(!repo.matches("[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"))throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Repository must be owner/name");}
 public record ConnectRequest(@NotBlank String token){} public record ConnectionResponse(Long id,String provider,String account,String status,java.time.Instant createdAt){static ConnectionResponse from(GitHubConnection c){return new ConnectionResponse(c.getId(),"GITHUB",c.getAccount(),"ACTIVE",c.getCreatedAt());}}
}
