package kz.zeroops.api;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/webhooks/github")
public class GitHubWebhookController {
 private final String secret; private final ObjectMapper json; private final WebhookEventRepository events; private final ProjectRepository projects; private final DeploymentRepository deployments; private final JobRepository jobs;
 public GitHubWebhookController(@Value("${GITHUB_WEBHOOK_SECRET:}") String secret,ObjectMapper json,WebhookEventRepository events,ProjectRepository projects,DeploymentRepository deployments,JobRepository jobs){this.secret=secret;this.json=json;this.events=events;this.projects=projects;this.deployments=deployments;this.jobs=jobs;}
 @PostMapping public WebhookResponse receive(@RequestHeader(value="X-GitHub-Delivery",required=false) String delivery,@RequestHeader(value="X-GitHub-Event",required=false) String event,@RequestHeader(value="X-Hub-Signature-256",required=false) String signature,@RequestBody byte[] body){if(secret.isBlank())throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"GitHub webhook secret is not configured");if(delivery==null||event==null||signature==null||!valid(signature,body))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid GitHub webhook signature");if(events.existsByDeliveryId(delivery))return new WebhookResponse("duplicate");try{JsonNode root=json.readTree(body);String repo=root.path("repository").path("html_url").asText();String full=root.path("repository").path("full_name").asText();String action=root.path("action").asText("");events.save(new WebhookEvent(delivery,event,full,action,"RECEIVED"));if("push".equals(event)){String branch=root.path("ref").asText().replace("refs/heads/","");String sha=root.path("after").asText();projects.findAllByOrderByCreatedAtDesc().stream().filter(p->p.isAutoDeploy()&&p.getRepositoryUrl().replaceAll("/$","").equals(repo.replaceAll("/$","") )&&p.getBranch().equals(branch)).forEach(p->{Deployment d=new Deployment(p.getSlug(),sha);d.attach(p);d=deployments.save(d);jobs.save(new Job(JobType.DEPLOY,p,d,"{\"source\":\"webhook\"}","push:"+delivery));});}else if("pull_request".equals(event)){jobs.save(new Job(JobType.WEBHOOK,null,null,"{\"event\":\"pull_request\",\"action\":\""+action.replace("\"","")+"\"}","pr:"+delivery));}return new WebhookResponse("accepted");}catch(Exception e){if(e instanceof ResponseStatusException r)throw r;throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Webhook payload cannot be processed");}}
 private boolean valid(String supplied,byte[] body){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));String expected="sha256="+java.util.HexFormat.of().formatHex(mac.doFinal(body));return MessageDigest.isEqual(expected.getBytes(StandardCharsets.UTF_8),supplied.getBytes(StandardCharsets.UTF_8));}catch(Exception e){return false;}}
 public record WebhookResponse(String status){}
}
