package kz.zeroops.api;
import com.fasterxml.jackson.databind.ObjectMapper; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import javax.crypto.*; import javax.crypto.spec.SecretKeySpec; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus;
@Service public class ManifestSigner {
 private final byte[] key; private final ObjectMapper json;
 public ManifestSigner(@Value("${MANIFEST_SIGNING_KEY:}")String secret,ObjectMapper json){this.json=json;try{key=secret.isBlank()?new byte[0]:Base64.getDecoder().decode(secret);}catch(Exception e){throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"MANIFEST_SIGNING_KEY is not valid base64");}}
 public SignedManifest issue(Deployment d){if(key.length<32)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Manifest signing is not configured");Project p=d.getProject();if(p.getTargetServer()==null)throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Deployment needs an ONLINE target server");Instant expiry=Instant.now().plusSeconds(300);DeploymentManifest manifest=new DeploymentManifest(1,d.getId(),p.getId(),p.getTargetServer().getId(),p.getRepositoryUrl(),p.getBranch(),d.getCommitSha(),p.getRuntime(),p.getApplicationPort(),"/health",p.getSlug()+":"+d.getCommitSha(),expiry,UUID.randomUUID().toString());try{String payload=Base64.getUrlEncoder().withoutPadding().encodeToString(json.writeValueAsBytes(manifest));return new SignedManifest(payload,sign(payload));}catch(Exception e){throw new IllegalStateException("Manifest cannot be encoded",e);}}
 private String sign(String payload){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(key,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(mac.doFinal(payload.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public record SignedManifest(String payload,String signature){}
}
