package kz.zeroops.api;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.Instant;
import java.util.List;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/v1/projects")
public class ProjectController {
  private final ProjectRepository projects; private final EnvironmentVariableRepository variables; private final DeploymentRepository deployments;
  private final JobRepository jobs; private final AnalyzerResultRepository analyses; private final SecretCodec secrets; private final CurrentUser current; private final ManagedServerRepository servers;
  public ProjectController(ProjectRepository projects, EnvironmentVariableRepository variables, DeploymentRepository deployments, JobRepository jobs, AnalyzerResultRepository analyses, SecretCodec secrets, CurrentUser current, ManagedServerRepository servers) { this.projects=projects;this.variables=variables;this.deployments=deployments;this.jobs=jobs;this.analyses=analyses;this.secrets=secrets;this.current=current;this.servers=servers; }
  @GetMapping public List<ProjectResponse> list(){AppUser user=current.require(); return (current.isAdmin(user)?projects.findAllByOrderByCreatedAtDesc():projects.findAllByOwnerIdOrderByCreatedAtDesc(user.getId())).stream().map(ProjectResponse::from).toList();}
  @PostMapping @ResponseStatus(HttpStatus.CREATED) public ProjectResponse create(@Valid @RequestBody ProjectRequest r){if(projects.existsBySlug(r.slug()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Project slug is already in use");Project p=new Project(r.name(),r.slug(),r.repositoryUrl(),r.branch(),r.runtime(),r.applicationPort(),r.publicPort(),r.healthPath());p.configureDelivery(blank(r.domain()),!Boolean.FALSE.equals(r.autoDeploy()));AppUser owner=current.require();p.assignOwner(owner);p.assignTargetServer(server(r.targetServerId(),owner));return ProjectResponse.from(projects.save(p));}
  @GetMapping("/{id}") public ProjectResponse get(@PathVariable Long id){return ProjectResponse.from(project(id));}
  @PutMapping("/{id}") public ProjectResponse update(@PathVariable Long id,@Valid @RequestBody ProjectRequest r){Project p=project(id);if(!p.getSlug().equals(r.slug()))throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Project slug cannot be changed");p.update(r.name(),r.repositoryUrl(),r.branch(),r.runtime(),r.applicationPort(),r.publicPort(),r.healthPath());p.configureDelivery(blank(r.domain()),!Boolean.FALSE.equals(r.autoDeploy()));p.assignTargetServer(server(r.targetServerId(),current.require()));return ProjectResponse.from(projects.save(p));}
  @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id){projects.delete(project(id));}
  @GetMapping("/{id}/variables") public List<VariableResponse> variables(@PathVariable Long id){project(id);return variables.findByProjectIdOrderByCreatedAtAsc(id).stream().map(VariableResponse::from).toList();}
  @PutMapping("/{id}/variables/{key}") @Transactional public VariableResponse putVariable(@PathVariable Long id,@PathVariable @Pattern(regexp="[A-Z_][A-Z0-9_]{0,127}") String key,@Valid @RequestBody VariableRequest r){Project p=project(id);String stored=r.secret()?secrets.encrypt(r.value()):r.value();EnvironmentVariable v=variables.findByProjectIdAndKey(id,key).map(x->{x.update(stored,r.secret());return x;}).orElseGet(()->new EnvironmentVariable(p,key,stored,r.secret()));return VariableResponse.from(variables.save(v));}
  @DeleteMapping("/{id}/variables/{key}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteVariable(@PathVariable Long id,@PathVariable String key){project(id);EnvironmentVariable v=variables.findByProjectIdAndKey(id,key).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Variable not found"));variables.delete(v);}
  @GetMapping("/{id}/deployments") public List<DeploymentResponse> deployments(@PathVariable Long id){project(id);return deployments.findAllByProjectIdOrderByCreatedAtDesc(id).stream().map(DeploymentResponse::from).toList();}
  @PostMapping("/{id}/deployments") @ResponseStatus(HttpStatus.ACCEPTED) public DeploymentResponse deploy(@PathVariable Long id,@Valid @RequestBody ProjectDeploymentRequest r){Project p=project(id);String commit=r.commitSha().isBlank()?"manual-"+Instant.now().toEpochMilli():r.commitSha();Deployment d=new Deployment(p.getSlug(),commit);d.attach(p);d=deployments.save(d);jobs.save(new Job(JobType.DEPLOY,p,d,"{\"runtime\":\""+p.getRuntime()+"\",\"port\":"+p.getApplicationPort()+"}",null));return DeploymentResponse.from(d);}
  @PostMapping("/{projectId}/deployments/{deploymentId}/rollback") @ResponseStatus(HttpStatus.ACCEPTED) @Transactional public DeploymentResponse rollback(@PathVariable Long projectId,@PathVariable Long deploymentId){Project p=project(projectId);Deployment failed=deployments.findById(deploymentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Deployment not found"));if(failed.getProject()==null||!failed.getProject().getId().equals(p.getId()))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Deployment not found for project");if(failed.getStatus()==DeploymentStatus.QUEUED||failed.getStatus()==DeploymentStatus.CHECKOUT)throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Cannot rollback a deployment that is not finished");Deployment previous=deployments.findFirstByProjectIdAndStatusAndIdNotOrderByCreatedAtDesc(projectId,DeploymentStatus.SUCCESS,deploymentId).orElseThrow(()->new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"No previous successful deployment is available"));failed.moveTo(DeploymentStatus.ROLLED_BACK);deployments.save(failed);Deployment rollback=new Deployment(p.getSlug(),previous.getCommitSha());rollback.attach(p);rollback=deployments.save(rollback);jobs.save(new Job(JobType.DEPLOY,p,rollback,"{\"source\":\"rollback\",\"fromDeployment\":"+deploymentId+"}","rollback:"+deploymentId));return DeploymentResponse.from(rollback);}
  @PostMapping("/{id}/analyze") @ResponseStatus(HttpStatus.ACCEPTED) public AnalyzerResponse analyze(@PathVariable Long id){Project p=project(id);AnalyzerResult a=analyses.save(new AnalyzerResult(p));jobs.save(new Job(JobType.ANALYZE,p,null,"{\"repositoryUrl\":\""+p.getRepositoryUrl().replace("\"","")+"\"}","analyze:"+id+":"+a.getId()));return AnalyzerResponse.from(a);}
  @GetMapping("/{id}/analysis") public AnalyzerResponse analysis(@PathVariable Long id){project(id);return analyses.findFirstByProjectIdOrderByCreatedAtDesc(id).map(AnalyzerResponse::from).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No analyzer result yet"));}
  private Project project(Long id){Project p=projects.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Project not found"));AppUser u=current.require();if(!current.isAdmin(u)&&(p.getOwner()==null||!p.getOwner().getId().equals(u.getId())))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Project access denied");return p;}
  private ManagedServer server(Long id,AppUser owner){if(id==null)return null;ManagedServer s=servers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Target server not found"));if(!current.isAdmin(owner)&&!s.getOwner().getId().equals(owner.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Target server access denied");if(s.getStatus()!=ServerStatus.ONLINE)throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Target server must be ONLINE");return s;}
  private static String blank(String v){return v==null||v.isBlank()?null:v;}
  public record ProjectRequest(@NotBlank @Size(min=2,max=100) String name,@NotBlank @Pattern(regexp="[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?") String slug,@NotBlank @Pattern(regexp="https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/?") String repositoryUrl,@NotBlank @Size(max=255) String branch,@NotNull ProjectRuntime runtime,@NotNull @Min(1) @Max(65535) Integer applicationPort,@NotNull @Min(1024) @Max(65535) Integer publicPort,@NotBlank @Pattern(regexp="/[A-Za-z0-9._~/%?-]{0,255}") String healthPath,@Pattern(regexp="^$|^[a-zA-Z0-9.-]+$") String domain,Boolean autoDeploy,Long targetServerId){}
  public record VariableRequest(@NotBlank @Size(max=10000) String value,boolean secret){}
  public record ProjectDeploymentRequest(@Pattern(regexp="^$|[A-Za-z0-9._-]{7,128}") String commitSha){public String commitSha(){return commitSha==null?"":commitSha;}}
  public record ProjectResponse(Long id,String name,String slug,String repositoryUrl,String branch,ProjectRuntime runtime,Integer applicationPort,Integer publicPort,String healthPath,String domain,boolean autoDeploy,Long targetServerId,Instant createdAt){static ProjectResponse from(Project p){return new ProjectResponse(p.getId(),p.getName(),p.getSlug(),p.getRepositoryUrl(),p.getBranch(),p.getRuntime(),p.getApplicationPort(),p.getPublicPort(),p.getHealthPath(),p.getDomain(),p.isAutoDeploy(),p.getTargetServer()==null?null:p.getTargetServer().getId(),p.getCreatedAt());}}
  public record VariableResponse(Long id,String key,String value,boolean secret,Instant createdAt){static VariableResponse from(EnvironmentVariable v){return new VariableResponse(v.getId(),v.getKey(),v.isSecret()?null:v.getValue(),v.isSecret(),v.getCreatedAt());}}
  public record DeploymentResponse(Long id,String projectSlug,String commitSha,DeploymentStatus status,String failureReason,Instant createdAt,Instant updatedAt){static DeploymentResponse from(Deployment d){return new DeploymentResponse(d.getId(),d.getProjectSlug(),d.getCommitSha(),d.getStatus(),d.getFailureReason(),d.getCreatedAt(),d.getUpdatedAt());}}
  public record AnalyzerResponse(Long id,JobStatus status,ProjectRuntime detectedRuntime,Integer applicationPort,String summary,String evidence,String errorMessage,Instant createdAt,Instant updatedAt){static AnalyzerResponse from(AnalyzerResult a){return new AnalyzerResponse(a.getId(),a.getStatus(),a.getDetectedRuntime(),a.getApplicationPort(),a.getSummary(),a.getEvidence(),a.getErrorMessage(),a.getCreatedAt(),a.getUpdatedAt());}}
}
