package kz.zeroops.api;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/servers") public class ServerController {
 private final ManagedServerRepository servers; private final EnrollmentTokenRepository enrollments; private final ServerHeartbeatRepository heartbeats; private final CurrentUser current; private final SecureRandom random=new SecureRandom();
 public ServerController(ManagedServerRepository servers,EnrollmentTokenRepository enrollments,ServerHeartbeatRepository heartbeats,CurrentUser current){this.servers=servers;this.enrollments=enrollments;this.heartbeats=heartbeats;this.current=current;}
 @GetMapping public List<ServerView> list(){AppUser u=current.require();return (current.isAdmin(u)?servers.findAll():servers.findAllByOwnerIdOrderByCreatedAtDesc(u.getId())).stream().map(ServerView::from).toList();}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public ServerView create(@Valid @RequestBody ServerRequest r){return ServerView.from(servers.save(new ManagedServer(current.require(),r.name(),r.host(),r.environment(),r.labels()==null?"{}":r.labels())));}
 @PutMapping("/{id}") public ServerView update(@PathVariable Long id,@Valid @RequestBody ServerRequest r){ManagedServer s=server(id);s.update(r.name(),r.host(),r.environment(),r.labels()==null?"{}":r.labels());return ServerView.from(servers.save(s));}
 @PostMapping("/{id}/enrollment") @ResponseStatus(HttpStatus.CREATED) public EnrollmentView enrollment(@PathVariable Long id){ManagedServer s=server(id);String raw=secret();enrollments.save(new EnrollmentToken(s,hash(raw),Instant.now().plus(Duration.ofMinutes(15))));return new EnrollmentView(raw,Instant.now().plus(Duration.ofMinutes(15)),"Show once; it cannot be retrieved again.");}
 @PostMapping("/{id}/disable") public ServerView disable(@PathVariable Long id){ManagedServer s=server(id);s.status(ServerStatus.DISABLED);return ServerView.from(servers.save(s));}
 @PostMapping("/{id}/maintenance") public ServerView maintenance(@PathVariable Long id){ManagedServer s=server(id);s.status(ServerStatus.MAINTENANCE);return ServerView.from(servers.save(s));}
 private ManagedServer server(Long id){ManagedServer s=servers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Server not found"));AppUser u=current.require();if(!current.isAdmin(u)&&!s.getOwner().getId().equals(u.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Server access denied");return s;} private String secret(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} static String hash(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public record ServerRequest(@NotBlank @Size(max=100) String name,@NotBlank @Pattern(regexp="[A-Za-z0-9._:-]{1,255}") String host,@NotBlank @Size(max=64) String environment,@Size(max=4000) String labels){} public record ServerView(Long id,String name,String host,String environment,String labels,ServerStatus status,Instant lastSeen){static ServerView from(ManagedServer s){return new ServerView(s.getId(),s.getName(),s.getHost(),s.getEnvironment(),s.getLabels(),s.getStatus(),s.getLastSeen());}} public record EnrollmentView(String token,Instant expiresAt,String notice){}
}
